name: Build and Push to Docker Hub

on:
  push:
    branches:
      - app
      - old_front

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Compose
      run: |
        docker-compose -f docker-compose.yaml build --no-cache
        docker-compose -f docker-compose.yaml push
